spring:
  application:
    name: avalon-config
  profiles: #配置文件本地
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/properties/
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 654321
security:
  username: avalon
  password: 123456
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.username}:${security.password}@avalon-eureka:8760/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
      base-path: /
  endpoint:
    health:
      show-details: always  #查看详细的应用健康信息需要配置    